include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "lib/gen/**"

linter:
  rules:
    # Logging & noise
    avoid_print: true

    # Consistency & readability
    prefer_single_quotes: true
    directives_ordering: true
    require_trailing_commas: true

    # Immutability & performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Types & API clarity
    always_declare_return_types: true
    avoid_dynamic_calls: true

    # Async safety
    unawaited_futures: true
    use_build_context_synchronously: true

    # Cleanups
    unnecessary_lambdas: true
    avoid_redundant_argument_values: true
