include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "lib/gen/**"
    - "scripts/**"
  errors:
    # Treat as errors (not just warnings)
    avoid_print: error
    unawaited_futures: warning
    use_build_context_synchronously: warning

linter:
  rules:
    # Logging & noise
    avoid_print: true

    # Consistency & readability
    prefer_single_quotes: true
    directives_ordering: true
    require_trailing_commas: true
    sort_child_properties_last: true
    prefer_is_empty: true

    # Immutability & performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    sized_box_for_whitespace: true

    # Types & API clarity
    always_declare_return_types: true
    avoid_dynamic_calls: true

    # Async safety
    unawaited_futures: true
    use_build_context_synchronously: true

    # Cleanups
    unnecessary_lambdas: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    prefer_const_declarations: true
