// Mocks generated by Mockito 5.4.6 from annotations
// in memozap/test/widgets/last_chance_banner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:memozap/models/shopping_list.dart' as _i2;
import 'package:memozap/models/smart_suggestion.dart' as _i4;
import 'package:memozap/models/unified_list_item.dart' as _i9;
import 'package:memozap/providers/shopping_lists_provider.dart' as _i7;
import 'package:memozap/providers/suggestions_provider.dart' as _i3;
import 'package:memozap/providers/user_context.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeShoppingList_0 extends _i1.SmartFake implements _i2.ShoppingList {
  _FakeShoppingList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SuggestionsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestionsProvider extends _i1.Mock
    implements _i3.SuggestionsProvider {
  MockSuggestionsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.SmartSuggestion> get suggestions =>
      (super.noSuchMethod(
            Invocation.getter(#suggestions),
            returnValue: <_i4.SmartSuggestion>[],
          )
          as List<_i4.SmartSuggestion>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasCurrentSuggestion =>
      (super.noSuchMethod(
            Invocation.getter(#hasCurrentSuggestion),
            returnValue: false,
          )
          as bool);

  @override
  int get pendingSuggestionsCount =>
      (super.noSuchMethod(
            Invocation.getter(#pendingSuggestionsCount),
            returnValue: 0,
          )
          as int);

  @override
  Set<String> get excludedProducts =>
      (super.noSuchMethod(
            Invocation.getter(#excludedProducts),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> removeFromExcluded(String? productName) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromExcluded, [productName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> refreshSuggestions() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSuggestions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addCurrentSuggestion(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#addCurrentSuggestion, [listId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dismissCurrentSuggestion() =>
      (super.noSuchMethod(
            Invocation.method(#dismissCurrentSuggestion, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCurrentSuggestion(Duration? duration) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrentSuggestion, [duration]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ShoppingListsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingListsProvider extends _i1.Mock
    implements _i7.ShoppingListsProvider {
  MockShoppingListsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.ShoppingList> get lists =>
      (super.noSuchMethod(
            Invocation.getter(#lists),
            returnValue: <_i2.ShoppingList>[],
          )
          as List<_i2.ShoppingList>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get isEmpty =>
      (super.noSuchMethod(Invocation.getter(#isEmpty), returnValue: false)
          as bool);

  @override
  List<_i2.ShoppingList> get activeLists =>
      (super.noSuchMethod(
            Invocation.getter(#activeLists),
            returnValue: <_i2.ShoppingList>[],
          )
          as List<_i2.ShoppingList>);

  @override
  List<_i2.ShoppingList> get completedLists =>
      (super.noSuchMethod(
            Invocation.getter(#completedLists),
            returnValue: <_i2.ShoppingList>[],
          )
          as List<_i2.ShoppingList>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  List<_i2.ShoppingList> getRecentLists(int? days) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentLists, [days]),
            returnValue: <_i2.ShoppingList>[],
          )
          as List<_i2.ShoppingList>);

  @override
  void updateUserContext(_i8.UserContext? newContext) => super.noSuchMethod(
    Invocation.method(#updateUserContext, [newContext]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> loadLists() =>
      (super.noSuchMethod(
            Invocation.method(#loadLists, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> retry() =>
      (super.noSuchMethod(
            Invocation.method(#retry, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearAll() => super.noSuchMethod(
    Invocation.method(#clearAll, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.ShoppingList> createList({
    required String? name,
    String? type = 'super',
    double? budget,
    DateTime? eventDate,
    bool? isShared = false,
    List<_i9.UnifiedListItem>? items,
    String? templateId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createList, [], {
              #name: name,
              #type: type,
              #budget: budget,
              #eventDate: eventDate,
              #isShared: isShared,
              #items: items,
              #templateId: templateId,
            }),
            returnValue: _i5.Future<_i2.ShoppingList>.value(
              _FakeShoppingList_0(
                this,
                Invocation.method(#createList, [], {
                  #name: name,
                  #type: type,
                  #budget: budget,
                  #eventDate: eventDate,
                  #isShared: isShared,
                  #items: items,
                  #templateId: templateId,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ShoppingList>);

  @override
  _i5.Future<void> deleteList(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteList, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> restoreList(_i2.ShoppingList? list) =>
      (super.noSuchMethod(
            Invocation.method(#restoreList, [list]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateList(_i2.ShoppingList? updated) =>
      (super.noSuchMethod(
            Invocation.method(#updateList, [updated]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i2.ShoppingList? getById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getById, [id]))
          as _i2.ShoppingList?);

  @override
  _i5.Future<void> addItemToList(
    String? listId,
    String? name,
    int? quantity,
    String? unit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addItemToList, [listId, name, quantity, unit]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addUnifiedItem(String? listId, _i9.UnifiedListItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addUnifiedItem, [listId, item]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeItemFromList(String? listId, int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeItemFromList, [listId, index]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateItemAt(
    String? listId,
    int? index,
    _i9.UnifiedListItem Function(_i9.UnifiedListItem)? updateFn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemAt, [listId, index, updateFn]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleAllItemsChecked(String? listId, bool? isChecked) =>
      (super.noSuchMethod(
            Invocation.method(#toggleAllItemsChecked, [listId, isChecked]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, int> getListStats(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getListStats, [listId]),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  _i5.Future<void> updateListStatus(String? listId, String? newStatus) =>
      (super.noSuchMethod(
            Invocation.method(#updateListStatus, [listId, newStatus]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> archiveList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveList, [listId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i9.UnifiedListItem> getUnpurchasedItems(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnpurchasedItems, [listId]),
            returnValue: <_i9.UnifiedListItem>[],
          )
          as List<_i9.UnifiedListItem>);

  @override
  _i5.Future<void> completeList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#completeList, [listId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> activateList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#activateList, [listId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addToNextList(List<_i9.UnifiedListItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#addToNextList, [items]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startCollaborativeShopping(String? listId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#startCollaborativeShopping, [listId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> joinCollaborativeShopping(String? listId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#joinCollaborativeShopping, [listId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveCollaborativeShopping(String? listId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveCollaborativeShopping, [listId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markItemAsChecked(
    String? listId,
    int? itemIndex,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markItemAsChecked, [listId, itemIndex, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> finishCollaborativeShopping(
    String? listId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#finishCollaborativeShopping, [listId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cleanupAbandonedSessions() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupAbandonedSessions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
