// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/fetch_product_images.py
// Run: python3 scripts/fetch_product_images.py
// Total images: 0 (run the script to populate)

/// Static map of product barcodes to image URLs.
/// Images sourced from Rami Levy (rami-levy.co.il).
const Map<String, String> productImageUrls = {};
