// lib/config/product_images_config.dart — CDN image URLs — Rami Levy + Shufersal + Open Food Facts, supports 7-13 digit barcodes

class ProductImagesConfig {
  ProductImagesConfig._();

  /// Rami Levy CDN base URL
  static const String _ramiLevyCdnBase = 'https://img.rami-levy.co.il/product';

  /// Shufersal Cloudinary base URL
  static const String _shufersalCdnBase =
      'https://res.cloudinary.com/shufersal/image/upload/f_auto,q_auto,w_200/v1/products/products_zoomed';

  /// Open Food Facts image base URL (global free product DB)
  /// URL format requires barcode split into groups: e.g.
  /// 7290116537849 → 729/011/653/7849
  static const String _openFoodFactsBase =
      'https://images.openfoodfacts.org/images/products';

  /// Tavliney-Pereg CDN base. Pereg's image filenames are internal SKU
  /// codes (e.g. "I843392"), not EAN barcodes — so the {barcode → SKU}
  /// map below is the only way to look these up. Generated by scraping
  /// the public catalog and fuzzy-matching against the supermarket.json
  /// items already tagged `brand: "פרג"` (see scripts/scrape_pereg_catalog.js
  /// + scripts/match_pereg_to_catalog.js).
  static const String _peregCdnBase =
      'https://www.tavlineypereg.co.il/ProductsImages';

  /// Barcode → Pereg internal SKU. 41 high-confidence matches.
  static const Map<String, String> _peregBarcodeToSku = {
    '7290015321426': 'D433526', // אורגנו
    '7290016492606': 'S584420', // סחוג
    '7290011091972': 'L165597', // עמבה אסלית
    '7290011090227': 'C90188', // רוזמרין
    '7290015321433': 'C90188', // רוזמרין
    '7290011091620': 'S323434', // קימל טחון
    '7290015321402': 'E182442', // כוסברה
    '7290015321273': 'P478463', // מלח לימון
    '7290015321389': 'S438088', // פטרוזיליה
    '7290011091507': 'W531777', // פלפל שחור טחון
    '7290014308633': 'W138711', // פלפל שחור שלם
    '7290015321419': 'P52300', // שמיר
    '7290011091088': 'F589364', // כורכום
    '7290015321570': 'I682336', // מלח הימלאיה דק
    '7290015321341': 'D187188', // חוויג' למרק
    '7290011091866': 'N420968', // פנקו גס
    '7290011091873': 'V575402', // פנקו עדין
    '7290015321297': 'U940591', // גריל עוף שקית 1 ק"ג
    '7290015321242': 'L123315', // קינמון טחון
    '7290015321440': 'Y288613', // עלי דפנה
    '7290003078684': 'W531777', // פלפל שחור טחון
    '7290015321358': 'Y624505', // חוויג' לקפה
    '7290015321235': 'L568322', // מקלות קינמון
    '7290014308978': 'L568322', // מקלות קינמון
    '7290015321198': 'Z427025', // פפריקה חריפה
    '7290015321174': 'Z961114', // פפריקה מתוקה בשמן תבליני פרג
    '7290011091057': 'Z961114', // פפריקה מתוקה בשמן תבליני פרג
    '7290016492354': 'Q177254', // שמן זית 5 ליטר
    '7290015321228': 'Y547936', // זנגביל טחון
    '7290015321457': 'K39773', // עלי טימין
    '7290015321211': 'I843392', // כמון טחון
    '7290008423021': 'I843392', // כמון טחון
    '7290003078721': 'S584420', // סחוג
    '7290014309036': 'B361306', // ציפורן שלמה
    '7290015321327': 'Z670830', // תבלין לדגים
    '7290015321396': 'N854653', // עלי בזיליקום
    '7290015321365': 'C751443', // זעתר בלאדי
    '7290008423236': 'P945641', // מלח גס גדול
    '7290008423229': 'W540642', // מלח דק גדול
    '7290008423045': 'W461541', // תבלין לקציצות ומפרום
    '7290015321310': 'Y133095', // תבלין לשווארמה ופרגיות
  };

  /// Standard barcode lengths (EAN-8, UPC-A, EAN-13) — used for
  /// Shufersal and Open Food Facts CDNs which require real EAN codes.
  static const Set<int> _standardEanLengths = {8, 12, 13};

  /// Rami Levy internal product IDs are typically 7 digits. Their CDN
  /// accepts both internal IDs and standard EAN barcodes, so we always
  /// include the Rami Levy URL regardless of barcode length.
  static const int _minBarcodeLength = 7;

  /// Generate all available image URLs for a barcode (primary first).
  /// Pereg CDN (when barcode is in the brand-specific map) is preferred
  /// over the supermarket CDNs because it shows the actual on-shelf
  /// packaging and rarely 404s. Falls through to Rami Levy → Shufersal
  /// → Open Food Facts for everything else.
  static List<String> getImageUrls(String? barcode) {
    if (barcode == null || barcode.length < _minBarcodeLength) {
      return const [];
    }
    final urls = <String>[];
    final peregSku = _peregBarcodeToSku[barcode];
    if (peregSku != null) {
      urls.add('$_peregCdnBase/$peregSku.jpg');
    }
    urls.add('$_ramiLevyCdnBase/$barcode/small.jpg');
    if (_standardEanLengths.contains(barcode.length)) {
      urls.add('$_shufersalCdnBase/$barcode');
      urls.add(_openFoodFactsUrl(barcode));
    }
    return urls;
  }

  /// Generate primary image URL from barcode (Rami Levy).
  /// Returns null if barcode is too short.
  static String? getImageUrl(String? barcode) {
    if (barcode == null || barcode.length < _minBarcodeLength) {
      return null;
    }
    return '$_ramiLevyCdnBase/$barcode/small.jpg';
  }

  /// Build Open Food Facts image URL from a barcode.
  /// Open Food Facts uses a directory structure: groups of 3 digits.
  /// For 13-digit EAN: AAA/BBB/CCC/DDDD
  /// For 12-digit UPC-A: it's converted to EAN-13 with leading 0.
  static String _openFoodFactsUrl(String barcode) {
    // Convert UPC-A (12) to EAN-13 by prepending '0'
    final ean13 = barcode.length == 12 ? '0$barcode' : barcode;

    if (ean13.length == 13) {
      // 13-digit: AAA/BBB/CCC/DDDD
      final p1 = ean13.substring(0, 3);
      final p2 = ean13.substring(3, 6);
      final p3 = ean13.substring(6, 9);
      final p4 = ean13.substring(9);
      return '$_openFoodFactsBase/$p1/$p2/$p3/$p4/front_he.200.jpg';
    } else {
      // 8-digit EAN-8: just the code
      return '$_openFoodFactsBase/$ean13/front_he.200.jpg';
    }
  }
}
