#!/usr/bin/env python3
"""
Fetch product image URLs from Rami Levy API.

This script queries the Rami Levy catalog API for each product barcode
and extracts the image URL. It outputs a Dart file with a static map
of barcode -> image URL that can be used in the Flutter app.

Usage:
    python3 scripts/fetch_product_images.py

Output:
    lib/config/product_image_urls.dart  (auto-generated Dart file)
    scripts/image_urls.json             (JSON backup)

Requirements:
    pip install requests
"""

import json
import os
import sys
import time
import requests

# ── Config ──────────────────────────────────────────────────────────
RAMI_LEVY_API = "https://www.rami-levy.co.il/api/catalog"
RAMI_LEVY_BASE = "https://www.rami-levy.co.il"
STORE_ID = 331  # Default store

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "he-IL,he;q=0.9,en;q=0.8",
    "Referer": "https://www.rami-levy.co.il/he/online/market",
    "Origin": "https://www.rami-levy.co.il",
}

# Delay between API requests (seconds) - be respectful
REQUEST_DELAY = 0.5

# ── Paths ───────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
PRODUCTS_JSON = os.path.join(PROJECT_DIR, "assets/data/list_types/supermarket.json")
OUTPUT_JSON = os.path.join(SCRIPT_DIR, "image_urls.json")
OUTPUT_DART = os.path.join(PROJECT_DIR, "lib/config/product_image_urls.dart")


def load_products():
    """Load product barcodes from supermarket.json."""
    with open(PRODUCTS_JSON, "r", encoding="utf-8") as f:
        products = json.load(f)

    # Extract unique barcodes with product names
    barcode_map = {}
    for p in products:
        bc = p.get("barcode", "")
        if bc and len(bc) >= 7:
            barcode_map[bc] = p.get("name", "")

    return barcode_map


def fetch_image_url(barcode, session):
    """Query Rami Levy API for a product's image URL."""
    try:
        resp = session.get(
            RAMI_LEVY_API,
            params={"store": STORE_ID, "q": barcode},
            headers=HEADERS,
            timeout=10,
        )
        resp.raise_for_status()
        data = resp.json()

        # Extract image URL from response
        products = data.get("data", [])
        if not products:
            return None

        product = products[0]

        # Try different image field paths
        images = product.get("images", {})
        if isinstance(images, dict):
            small = images.get("small", "")
            if small:
                if small.startswith("http"):
                    return small
                return f"{RAMI_LEVY_BASE}{small}"

        # Try direct image field
        img = product.get("image", "") or product.get("img", "")
        if img:
            if img.startswith("http"):
                return img
            return f"{RAMI_LEVY_BASE}{img}"

        return None

    except Exception as e:
        print(f"  Error fetching {barcode}: {e}")
        return None


def generate_dart_file(url_map):
    """Generate a Dart file with a static barcode -> URL map."""
    lines = [
        "// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
        "// Generated by scripts/fetch_product_images.py",
        f"// Last generated: {time.strftime('%Y-%m-%d %H:%M')}",
        f"// Total images: {len(url_map)}",
        "",
        "/// Static map of product barcodes to image URLs.",
        "/// Images sourced from Rami Levy (rami-levy.co.il).",
        "const Map<String, String> productImageUrls = {",
    ]

    for barcode, url in sorted(url_map.items()):
        lines.append(f"  '{barcode}': '{url}',")

    lines.append("};")
    lines.append("")

    with open(OUTPUT_DART, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nDart file written: {OUTPUT_DART}")


def main():
    print("=" * 60)
    print("Rami Levy Product Image URL Fetcher")
    print("=" * 60)

    # Load products
    barcode_map = load_products()
    total = len(barcode_map)
    print(f"\nFound {total} unique products with barcodes.")

    # Check for existing results (resume support)
    existing = {}
    if os.path.exists(OUTPUT_JSON):
        with open(OUTPUT_JSON, "r", encoding="utf-8") as f:
            existing = json.load(f)
        print(f"Found {len(existing)} existing results. Will skip those.")

    # Fetch image URLs
    url_map = dict(existing)
    session = requests.Session()

    barcodes = [bc for bc in barcode_map if bc not in existing]
    found = 0
    errors = 0

    print(f"\nFetching {len(barcodes)} remaining products...")
    print("(Press Ctrl+C to stop - progress is saved automatically)\n")

    try:
        for i, barcode in enumerate(barcodes):
            name = barcode_map[barcode]
            print(f"  [{i+1}/{len(barcodes)}] {name} ({barcode})...", end=" ")

            url = fetch_image_url(barcode, session)

            if url:
                url_map[barcode] = url
                found += 1
                print(f"OK")
            else:
                errors += 1
                print(f"not found")

            # Save progress every 50 products
            if (i + 1) % 50 == 0:
                with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
                    json.dump(url_map, f, ensure_ascii=False, indent=2)
                print(f"  --- Saved progress ({len(url_map)} URLs) ---")

            time.sleep(REQUEST_DELAY)

    except KeyboardInterrupt:
        print("\n\nInterrupted! Saving progress...")

    # Save final results
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(url_map, f, ensure_ascii=False, indent=2)

    print(f"\n{'=' * 60}")
    print(f"Results: {found} found, {errors} not found")
    print(f"Total URLs collected: {len(url_map)}")
    print(f"JSON saved: {OUTPUT_JSON}")

    # Generate Dart file
    if url_map:
        generate_dart_file(url_map)

    print(f"\nDone!")


if __name__ == "__main__":
    main()
